### ISSUE TITLE
Only first 10 pages of chat are saved

### ISSUE THREAD

**Issue by gohamstergo** [gildas-lormeau/single-file-export-chat#1]
When I run the extension on a lengthy chat (3 month retention, probably 50+ pages) all of the pages seem to be scrolled through and captured, I let it sit and process until the save dialog pops up on its own, save, open the html and only the first 10 pages or so are in the file. Let me know what only info you might need. Of course I can't share the chats, but if there is some info in the html you mint want, I'll do my best to get it.

**Comment by gildas-lormeau** [comment]
Thank you for reporting the issue. I made some changes in the implementation which hopefully should fix this limitation. Can you install the zip file of the extension (https://github.com/gildas-lormeau/single-file-export-chat/blob/main/singlefile-extension.zip) and try again?

**Comment by gohamstergo** [comment]
Thanks for looking into it so quickly. It does save properly now, but the behavior is a little different: In the previous version, it would scroll the chat, then show a view of the whole, tiny chat in a tab while it processed. Now, after scrolling, the tab freezes while it processes so Chrome reports the tab as unresponsive and asks to close it. However, if the user is patient and just waits, it will finish after a few minutes and pop up the save dialog.

**Comment by gildas-lormeau** [comment]
I agree that the user experience would be better without any freeze. I don't think I will be able to circumvent it unfortunately.

**Comment by gohamstergo** [comment]
Gotcha. Thanks for the help. This is a needed extension. Hopefully more folks discover it. But not too many that M$ tries to block it!

**Comment by ceecodes** [comment]
I'm having this issue as well. I used the extension in firefox, however if I try to open it in Microsoft Edge, it loads the first ten messages and then the page times out.
